// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Postie.Api.Data;

namespace Postie.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210422205900_AddUserBoardPost")]
    partial class AddUserBoardPost
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13");

            modelBuilder.Entity("Postie.Api.Models.Db.Board", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CreatedByID");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Postie.Api.Models.Db.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BoardID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("BoardID");

                    b.HasIndex("CreatedByID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Postie.Api.Models.Db.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthId")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Postie.Api.Models.Db.Board", b =>
                {
                    b.HasOne("Postie.Api.Models.Db.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByID");
                });

            modelBuilder.Entity("Postie.Api.Models.Db.Post", b =>
                {
                    b.HasOne("Postie.Api.Models.Db.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardID");

                    b.HasOne("Postie.Api.Models.Db.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByID");
                });
#pragma warning restore 612, 618
        }
    }
}
